# Generated by Django 3.2.23 on 2024-12-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['lat', 'lon'], name='route_optim_lat_a8415f_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['city'], name='route_optim_city_2d1428_idx'),
        ),
    ]
